version: '2'

services:
    mysql:
        image: mysql:5.6
        env_file:
            - .env
        volumes:
            - database:/var/lib/mysql
        ports:
            - "3307:3306"

    magento:
        image: ricardotulio/ecommerce-platforms
        volumes:
            - ./www/:/var/www/
        ports:
            - "8080:80"
            - "80:80"
        depends_on:
            - mysql

volumes:
    database:
        driver: local
